/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./src/components/Auth.vue')['default']
    Login: typeof import('./src/components/LoginView.vue')['default']
    LoginView: typeof import('./src/components/LoginView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tasks: typeof import('./src/components/Tasks.vue')['default']
    TaskTimer: typeof import('./src/components/TaskTimer.vue')['default']
  }
}
